/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nis1529' at '10/1/16 6:44 PM' with Gradle 3.1
 *
 * @author nis1529, @date 10/1/16 6:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
