/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'nis1529' at '10/1/16 6:44 PM' with Gradle 3.1
 *
 * @author nis1529, @date 10/1/16 6:44 PM
 */

import spock.lang.Specification

class LibrarySpec extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
